# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application source
COPY . .

# Build the project
RUN npm run build

# Expose any necessary ports if needed
EXPOSE 3000

# Start the server
CMD ["node", "dist/index.js"]
